export const BLOCKED_CRAWLERS = [
  "SemrushBot",
  "SemrushBot-BA",
  "SemrushBot-SI",
  "SemrushBot-SWA",
  "SemrushBot-OCOB",
  "SemrushBot-FT",
  "SemrushBot-ESI",
  "SiteAuditBot",
  "SplitSignalBot",
  "RyteBot",
  "AhrefsBot",
  "AhrefsSiteAudit",
  "MJ12bot",
  "DotBot",
  "BLEXBot",
  "DataForSeoBot",
  "PetalBot",
  "SeekportBot",
  "serpstatbot",
];

export const ALLOWED_BOT_CATEGORIES = [
  "Search Engine Crawler",
  "AI Search",
  "AI Assistant",
  "Page Preview",
  "Feed Fetcher",
  "Archiver",
];
